language: go

go:
  - tip
  - "1.11"
  - "1.10"

before_install:
  - go get -u github.com/golang/dep/cmd/dep
  - go get -u golang.org/x/tools/cmd/cover
  - go get -u github.com/mattn/goveralls

install:
  - dep ensure

script:
  - make build
  - make coveralls

notifications:
  slack: $SLACK_TOKEN
