language: go

go:
  - tip
  - "1.11"
  - "1.10"

before_install:
  - go get -u github.com/golang/dep/cmd/dep
  - go get -u golang.org/x/tools/cmd/cover
  - go get -u github.com/mattn/goveralls

install:
  - dep ensure

script:
  - make build
  - make coveralls

notifications:
  slack:
    secure: "cQSK2CvCOWCyrZX9xfT4w9/eq3WfMUjrWkD6+A246UztLc/t6TjXIJ37B3Nv20dssPiEiUE53PlBsrHVBpfewpUmC3GH0BV1ZYg2KPhyfXV8yRaO4hoyiIrG0HngX1MrJHeVJ2KdSspOCYPtaL0D5PCI/Oeo0OK6qh33LJNsAezwZQ6N624xVHp08wiFcoS7NyW50hvlCSuHU5TKr6HSly6Tv+46GpXmk2w6H0xfEbZKgq0j6855QWpnFdLNDIMewqjMprbU9O0ghrRI6ntvtQ0hmp2e23LEdkAZTm/eznlY4EcxsYfBAdOHVFJcSzQXTNBSOGXw1aEvws8g9NOpBqmJ549YnfwcVjEWdMzeD3EIE2VzzjrZ9EpGO0hKPwpQk87EEkRYJu/rXlihj+Od6oq9iNuFOx+Vgw5pYQb+F4XcJb+lwtwxMTBNoy5p/kCKVKsajYGE3vAOOvA2+V4xy60zVivkGwiSSJnHT6osmyI8Zzv8VXAk/wYSIbuM7rV1S9KPfZ+E3bu2mBKj+e0CGrBow7Le8pUtZZMx+/S1mRW7F/kGS40zRIOh5ErZVkXgYlBeMucnWRdAuVeiups+i/bX7i1dsrWk5ZwKJo7RHlyL9gLvczmZ2zumw1aKWAX/K0TQRRyORSmyBDEmqqIXIex3Ha+/a6V0jXk1MNSKlUg="
